### ISSUE TITLE
Window content has a margin and scrollbar outside visible area

### ISSUE THREAD

**Issue by tschf** [Dani3lSun/apex-app-desktop#3]
On my Ubuntu system, when running the app, half the scrollbar seems missing (Even when trying to resize). In fact in seems the actual content has a left and top margin applied (which picks up visuals from other parts of the system).

If I maximize and restore the window, it's picking up my system panel:

![image](https://cloud.githubusercontent.com/assets/1747643/12480994/50471f48-c09a-11e5-85be-df0f2557eacf.png)

**Comment by Dani3lSun** [comment]
Hi @tschf 
thanks for the feedback! I optimized the app frame to fit best in Mac OS X, thus it could be not so nice in other envs (not really tested)...
To fix that you should remove the following from main.js:

```
    "transparent": true, // better look in OSX
    "title-bar-style": "hidden-inset", // better look in OSX
```

Can you test that?

**Comment by tschf** [comment]
Removing those two lines, the margin is still there and is just white in this case (doesn't pick up visuals from other parts of the system).

**Comment by Dani3lSun** [comment]
should work now!:)

**Comment by tschf** [comment]
Yeah, much better :)
Good stuff.
